### ISSUE TITLE
hello_triangle: renders a rectangle

### ISSUE THREAD

**Issue by nektro** [cshenton/learnopengl#2]
**versions**:
```
zig 0.6.0
OpenGL version string: 4.6.0 NVIDIA 418.113
Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux
```

installed using: https://snapcraft.io/zig

**expected**:

a triangle

**actual**:

![image](https://user-images.githubusercontent.com/5464072/88267479-e52c3480-cc9e-11ea-9df4-ffec7f4bbd87.png)

**Comment by DerTee** [comment]
I feel like this is purely an issue with wording of the [original tutorial](https://learnopengl.com/Getting-started/Hello-Triangle), where the final result is also a rectangle and only the intermediary result is a triangle.
Also I don't think that it is problematic. Do you think it's a problem @nektro ? If so, why?

**Comment by nektro** [comment]
No, I'd agree with that assessment. Sorry for the issue.
